export const FETCH_IMAGE = 'FETCH_IMAGE';
export const FETCH_IMAGE_SUCCESS = 'FETCH_IMAGE_SUCCESS';
export const FETCH_IMAGE_ERROR = 'FETCH_IMAGE_ERROR';

export const ADD_ITEM_TO_HISTORY = 'ADD_ITEM_TO_HISTORY';
export const DELETE_ITEM_FROM_HISTORY = 'DELETE_ITEM_FROM_HISTORY';
